# Generated by Django 5.2.15 on 2026-06-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=200, unique=True)),
                ('remitente', models.CharField(max_length=300)),
                ('asunto', models.CharField(max_length=500)),
                ('fecha', models.CharField(max_length=100)),
                ('cuerpo', models.TextField(blank=True)),
                ('snippet', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, choices=[('trabajo', 'Trabajo'), ('personal', 'Personal'), ('spam', 'Spam'), ('promociones', 'Promociones'), ('importante', 'Importante'), ('informativo', 'Informativo')], max_length=50)),
                ('resumen_ia', models.TextField(blank=True)),
                ('leido', models.BooleanField(default=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_sincronizacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Correo',
                'verbose_name_plural': 'Correos',
                'ordering': ['-fecha_sincronizacion'],
            },
        ),
    ]
