# Generated by Django 5.2.15 on 2026-06-08 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correo',
            options={'ordering': ['-fecha'], 'verbose_name': 'Correo', 'verbose_name_plural': 'Correos'},
        ),
        migrations.AlterField(
            model_name='correo',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CuentaGmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token_json', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_gmail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de Gmail',
                'verbose_name_plural': 'Cuentas de Gmail',
            },
        ),
        migrations.AddField(
            model_name='correo',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='correo.cuentagmail'),
        ),
    ]
